// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVlWQiZWIeQvI0kjeDjNWwoWct0NxbI_w',
    appId: '1:420729488538:web:fb8f7100b03b80c723cb23',
    messagingSenderId: '420729488538',
    projectId: 'bustrackerapp-9828e',
    authDomain: 'bustrackerapp-9828e.firebaseapp.com',
    databaseURL: 'https://bustrackerapp-9828e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bustrackerapp-9828e.firebasestorage.app',
    measurementId: 'G-9PPF1ZED51',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcWZbFIPeU5lxYkTYLFhs3hdBBy8QI9-U',
    appId: '1:420729488538:ios:8a73f19c0a31448b23cb23',
    messagingSenderId: '420729488538',
    projectId: 'bustrackerapp-9828e',
    databaseURL: 'https://bustrackerapp-9828e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bustrackerapp-9828e.firebasestorage.app',
    iosBundleId: 'com.example.busTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcWZbFIPeU5lxYkTYLFhs3hdBBy8QI9-U',
    appId: '1:420729488538:ios:8a73f19c0a31448b23cb23',
    messagingSenderId: '420729488538',
    projectId: 'bustrackerapp-9828e',
    databaseURL: 'https://bustrackerapp-9828e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bustrackerapp-9828e.firebasestorage.app',
    iosBundleId: 'com.example.busTrackerApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIZpTUk2UuSe_gFBWkrIe9thKb6MoAT6I',
    appId: '1:420729488538:android:9a1d066234a9e11823cb23',
    messagingSenderId: '420729488538',
    projectId: 'bustrackerapp-9828e',
    databaseURL: 'https://bustrackerapp-9828e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bustrackerapp-9828e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVlWQiZWIeQvI0kjeDjNWwoWct0NxbI_w',
    appId: '1:420729488538:web:57a0df4bff67437023cb23',
    messagingSenderId: '420729488538',
    projectId: 'bustrackerapp-9828e',
    authDomain: 'bustrackerapp-9828e.firebaseapp.com',
    databaseURL: 'https://bustrackerapp-9828e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bustrackerapp-9828e.firebasestorage.app',
    measurementId: 'G-85SE2WM80G',
  );

}